# Generated by Django 5.2.14 on 2026-05-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('icon_url', models.CharField(default='/images/drone_hub_icon.png', max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
